const fs=require('fs');const path=require('path');
const DIST=path.join(__dirname,'..','dist');
const BASE='https://toolatlas.online';
const GA='G-8S04TV7EFG';
const categories={finance:'Finance tools and calculators',education:'Education calculators and study tools',travel:'Travel calculators and trip tools',engineering:'Engineering calculators and technical tools',math:'Math calculators and problem solvers',work:'Work, salary and pay calculators',conversion:'Unit converters and conversion tools',everyday:'Everyday calculators and useful tools',health:'Health and wellness calculators'};
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function walk(dir,out=[]){if(!fs.existsSync(dir))return out;for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p,out);else if(e.name==='index.html')out.push(p);}return out;}
const pages=walk(DIST);const records=[];
for(const file of pages){const rel=path.relative(DIST,path.dirname(file)).replace(/\\/g,'/');const html=fs.readFileSync(file,'utf8');const title=(html.match(/<title>([^<]*)<\/title>/i)||[])[1]||'ToolAtlas';const desc=(html.match(/<meta[^>]+name=[\"']description[\"'][^>]+content=[\"']([^\"']*)[\"']/i)||[])[1]||'Free online tools from ToolAtlas.';records.push({file,rel,title,desc});}
const favicon='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"%3E%3Crect width="64" height="64" rx="14" fill="%23071019"/%3E%3Cpath d="M16 17h32v8H36v23h-8V25H16z" fill="%2355e7ff"/%3E%3Ccircle cx="44" cy="44" r="6" fill="%23b9ff5a"/%3E%3C/svg%3E';
const ga=`<script async src="https://www.googletagmanager.com/gtag/js?id=${GA}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${GA}');</script>`;
for(const r of records){let html=fs.readFileSync(r.file,'utf8');const canonical=BASE+(r.rel?'/'+r.rel+'/':'/');const cat=Object.keys(categories).find(c=>r.rel.startsWith(c+'/'))||null;const catName=cat?cat[0].toUpperCase()+cat.slice(1):null;const existingFavicon=/rel=["'](?:icon|shortcut icon|apple-touch-icon)["']/i.test(html);const extra=`<link rel="icon" href="${favicon}" type="image/svg+xml"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23071019'/%3E%3Cpath d='M16 17h32v8H36v23h-8V25H16z' fill='%2355e7ff'/%3E%3Ccircle cx='44' cy='44' r='6' fill='%23b9ff5a'/%3E%3C/svg%3E"><link rel="apple-touch-icon" href="/favicon.svg"><meta name="theme-color" content="#071019"><meta property="og:type" content="website"><meta property="og:site_name" content="ToolAtlas"><meta property="og:title" content="${esc(r.title)} | ToolAtlas"><meta property="og:description" content="${esc(r.desc)}"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(r.title)} | ToolAtlas"><meta name="twitter:description" content="${esc(r.desc)}">`;
let schema={"@context":"https://schema.org","@type":"WebApplication","name":r.title,"url":canonical,"description":r.desc,"applicationCategory":"UtilitiesApplication","operatingSystem":"Any","isAccessibleForFree":true,"publisher":{"@type":"Organization","name":"ToolAtlas","url":BASE}};
if(r.rel){schema.category=catName||'Online Tools';}
if(cat){schema.breadcrumb={"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'ToolAtlas',item:BASE+'/'},{"@type":"ListItem",position:2,name:catName,item:BASE+'/'+cat+'/'},{"@type":"ListItem",position:3,name:r.title,item:canonical}]};}
const json=`<script type="application/ld+json">${JSON.stringify(schema)}</script>`;
if(/<head[^>]*>/i.test(html)) html=html.replace(/<head[^>]*>/i,m=>m+extra+json+ga); else html=extra+json+ga+html;
fs.writeFileSync(r.file,html);
}
const iconSvg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#071019"/><path d="M16 17h32v8H36v23h-8V25H16z" fill="#55e7ff"/><circle cx="44" cy="44" r="6" fill="#b9ff5a"/></svg>';
fs.writeFileSync(path.join(DIST,'favicon.svg'),iconSvg);fs.writeFileSync(path.join(DIST,'apple-touch-icon.svg'),iconSvg);
fs.writeFileSync(path.join(DIST,'site.webmanifest'),JSON.stringify({name:'ToolAtlas',short_name:'ToolAtlas',start_url:'/',display:'standalone',background_color:'#071019',theme_color:'#071019',icons:[{src:'/favicon.svg',sizes:'any',type:'image/svg+xml'}]},null,2));
const intro={finance:'Money, pricing, loans, savings, investing and business calculators.',education:'Grade, GPA, exam, study and admissions calculators for students.',travel:'Fuel, trip, pace, driving and travel-planning calculators.',engineering:'Physics, electrical, mechanical, aerospace and technical calculators.',math:'Percentages, ratios, fractions, geometry, statistics and number tools.',work:'Salary, hourly pay, overtime, freelance and workplace calculators.',conversion:'Fast converters for length, mass, volume, speed, pressure, energy, power, time and data.',everyday:'Simple tools for everyday decisions, costs, dates and measurements.',health:'General wellness calculators for informational use.'};
for(const [id,name] of Object.entries(categories)){const list=records.filter(r=>r.rel.startsWith(id+'/' )||(!id&&false));if(!list.length)continue;const cards=list.map(r=>`<a class="card" href="/${r.rel}/"><b>${esc(r.title)}</b><span>${esc(r.desc)}</span></a>`).join('');const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${name} | ToolAtlas</title><meta name="description" content="${intro[id]}"><link rel="canonical" href="${BASE}/${id}/"><link rel="icon" href="/favicon.svg"><meta name="theme-color" content="#071019"><meta property="og:title" content="${name} | ToolAtlas"><meta property="og:description" content="${intro[id]}"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":name,"url":BASE+'/'+id+'/',"description":intro[id],"isPartOf":{"@type":"WebSite","name":"ToolAtlas","url":BASE+'/'}})}</script><style>:root{--bg:#071019;--panel:#0d1b27;--line:#ffffff14;--text:#f5f8fb;--muted:#8ea2b1;--cyan:#55e7ff;--lime:#b9ff5a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#17364c,#071019 45%);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{max-width:1160px;margin:auto;padding:0 22px}.nav{height:70px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:1000;font-size:22px;letter-spacing:-.06em}.brand span{color:var(--cyan)}a{color:inherit;text-decoration:none}.back{font-size:10px;color:var(--muted)}.hero{padding:65px 0 38px}.ey{font-size:8px;color:var(--cyan);font-weight:900;letter-spacing:.14em;text-transform:uppercase}.hero h1{font-size:clamp(40px,7vw,72px);letter-spacing:-.07em;line-height:.92;margin:12px 0}.hero p{max-width:700px;color:var(--muted);font-size:14px;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card{padding:16px;border:1px solid var(--line);border-radius:14px;background:#0b1924}.card:hover{border-color:#55e7ff45;transform:translateY(-2px)}.card b{display:block;font-size:11px}.card span{display:block;color:#8fa3b1;font-size:8px;line-height:1.5;margin-top:6px}.foot{padding:45px 0;color:#647782;font-size:8px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.grid{grid-template-columns:1fr}}</style></head><body><div class="wrap"><header class="nav"><a class="brand" href="/">TOOL<span>ATLAS</span></a><a class="back" href="/">← All tools</a></header><main><section class="hero"><div class="ey">ToolAtlas · ${esc(name)}</div><h1>${esc(name)}</h1><p>${esc(intro[id])} Browse the full collection below.</p></section><section class="grid">${cards}</section></main><footer class="foot">ToolAtlas · Free online tools for everyone.</footer></div>${ga}</body></html>`;fs.mkdirSync(path.join(DIST,id),{recursive:true});fs.writeFileSync(path.join(DIST,id,'index.html'),html);}
const urls=[BASE+'/'];for(const r of records)urls.push(BASE+'/'+r.rel+'/');for(const id of Object.keys(categories))urls.push(BASE+'/'+id+'/');
const now=new Date().toISOString().slice(0,10);fs.writeFileSync(path.join(DIST,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(urls)].map(u=>`<url><loc>${u}</loc><lastmod>${now}</lastmod></url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(DIST,'robots.txt'),'User-agent: *\nAllow: /\nDisallow: /404\nSitemap: '+BASE+'/sitemap.xml\n');
fs.writeFileSync(path.join(DIST,'404.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page Not Found | ToolAtlas</title><link rel="icon" href="/favicon.svg"><meta name="theme-color" content="#071019"></head><body style="margin:0;background:#071019;color:#f5f8fb;font-family:system-ui;text-align:center;padding:15vh 20px"><div style="font-size:70px;font-weight:900;letter-spacing:-.08em">404</div><p style="color:#8ea2b1">That tool doesn't exist.</p><a href="/" style="color:#55e7ff;font-weight:800">Back to ToolAtlas →</a></body></html>`);
console.log(`SEO finish complete: ${records.length} generated pages + ${Object.keys(categories).length} category hubs.`);
